Add pre-commit
NSLS-II/edrixs pull request #144
Opened 2022-01-13 17:45 UTC by Anselmoo

Fixed issue #143

1. Add pre-commit
2. Apply pre-commit to all files
3. Add pre-commit to docs

2022-01-13 18:15 UTC, mpmdean commented
Thanks @Anselmoo. 

To my untrained eye, I would anticipate this being good practice and not something that will cause any issues. Something that jumps out in the file review is that quite a few Fortran and Fortan configuration files get touched in this change. 

Having tried to run some of the Cowan and related codes, I know that Fortran can sometimes be annoyingly sensitive to things like whitespace and new lines. Can @shenmidelin and @mrakitin have a look here? Thanks!

2022-01-13 19:07 UTC, Anselmoo commented
> Thanks @Anselmoo.
> 
> To my untrained eye, I would anticipate this being good practice and not something that will cause any issues. Something that jumps out in the file review is that quite a few Fortran and Fortan configuration files get touched in this change.
> 
> Having tried to run some of the Cowan and related codes, I know that Fortran can sometimes be annoyingly sensitive to things like whitespace and new lines. Can @shenmidelin and @mrakitin have a look here? Thanks!

Thx for the quick feedback @mpmdean 

Indeed, we can leave FORTRAN code out! Due to the comment in PR #143, I thought it is a good point to track this in a general way. Especially the python code contains kind of a lot of whitespaces.

What I personally like a lot is the fact, that you can include all linters (black, mypy, pydocstyle, ...) straight into the pre-commit. In this regard, this hook for FORTRAN might be interesting? [https://github.com/pseewald/fprettify](https://github.com/pseewald/fprettify)

2022-01-13 21:10 UTC, mpmdean commented
I'd propose to apply the pre-commit to only .py and .rst. I presume that's easily done?  What do other think?

BTW. I believe all our important python passes these. Just ours docs are exempt for now, which is probably lazyness on my part.

2022-01-13 21:14 UTC, Anselmoo commented
That's a good idea to start with 
`python`, `rst`, and maybe `JSON `first and include other formats, later. I will exclude the rest out of the general `pre-commit` hook.

2022-01-14 19:05 UTC, mrakitin reviewed
Looks good to me. I am happy with the hook applied to the .py and .rst files, not sure about the .f90, as @mpmdean mentioned that can break the code.

@Anselmoo, can you please explain how it's supposed to work? Will the workflow automatically _commit_ the linted changes, or will it just fail and a human will need to fix things manually? I am not currently using any pre-commit hooks, would be good to learn about them more. Thanks!

2022-01-14 19:05 UTC, mrakitin commented on github_deploy_key_nsls_ii_edrixs.enc
> +gAAAAABcpRg8HyudK4hJnRn96LjYReieR-hsjaarFdOpXiabUGsS1et3PhhIhphGBVaDxx4YGRb97wxHF6DVow9MP67XRIhZdcGN5A5Aoe0YtaymtuiitQlCzojwaoknx7eCOZ8WaZkwJKH_T2AYKpaWfZkWCYDpH_6Wql_z3_CP-geSviU7VTVal4oTJxuSgPmgRjR
This file may not be needed anymore, as the docs are now published by means other than `doctr` (implemented via #125).

2022-01-14 19:57 UTC, Anselmoo commented
> Looks good to me. I am happy with the hook applied to the .py and .rst files, not sure about the .f90, as @mpmdean mentioned that can break the code.
> 
> @Anselmoo, can you please explain how it's supposed to work? Will the workflow automatically _commit_ the linted changes, or will it just fail and a human will need to fix things manually? I am not currently using any pre-commit hooks, would be good to learn about them more. Thanks!

In general [https://github.com/pre-commit/pre-commit](https://github.com/pre-commit/pre-commit) is python package, which have first install via

1.  `pre-commit install`
2. `pre-commit run --all-files` is good for the first run to check current status quo
3. Next every git-push will run over `pre-commit` and block if the commit does not fulfill the requirements. In the case of `whitespace`, `isort` or `black`, it will automatically reformat. In case of flake8 it will block so long you are not fixing the fail.

If you want, we can add an extended comment in the **README**. I will restore the `*.f90` files and include an exclude.

2022-01-14 21:38 UTC, mrakitin commented
Thanks! I think it'd make sense to include the comment about setting up the recommit hooks in the dev section of the docs and/or README.

2022-01-15 22:36 UTC, mpmdean requested changes
Thanks @Anselmoo 

There seem to be a couple of files in `src` that still get changed in this PR. Can you check this?

2022-01-15 22:36 UTC, mpmdean commented on github_deploy_key_nsls_ii_edrixs.enc
> +gAAAAABcpRg8HyudK4hJnRn96LjYReieR-hsjaarFdOpXiabUGsS1et3PhhIhphGBVaDxx4YGRb97wxHF6DVow9MP67XRIhZdcGN5A5Aoe0YtaymtuiitQlCzojwaoknx7eCOZ8WaZkwJKH_T2AYKpaWfZkWCYDpH_6Wql_z3_CP-geSviU7VTVal4oTJxuSgPmgRjR
I would suggest not changing this in this PR. I will raise an issue about this

2022-01-15 22:36 UTC, mpmdean commented on src/Makefile
>  	rm -f *.x
I believe that these files should not be changed? As they are in the `src` folder?

2022-01-15 22:36 UTC, mpmdean commented on src/full_diag.f90
I believe that these files should not be changed? As they are in the `src` folder?

2022-01-15 22:36 UTC, mpmdean commented on src/io.f90
I believe that these files should not be changed? As they are in the `src` folder?

2022-01-18 19:11 UTC, Anselmoo commented
Sorry @mpmdean for Late reply. 
As mentioned in the code review, it is end of line trimming. Sometimes it was previously included, sometimes not. Now, it's consistent 
However, if you prefer, I will keeps `src` completely untouched?

2022-01-18 19:51 UTC, mpmdean commented
> Sorry @mpmdean for Late reply. As mentioned in the code review, it is end of line trimming. Sometimes it was previously included, sometimes not. Now, it's consistent However, if you prefer, I will keeps `src` completely untouched?

If you don't mind let's leave 
`src/*` 
`docs/user_guide.lyx`
`github_deploy_key_nsls_ii_edrixs.enc`

totally untouched. I'm not knowledgeable enough to know this won't cause problems and since these files are barely read there's not much advantage to cleaning them up.

2022-01-19 00:45 UTC, mpmdean approved these changes

2022-01-25 16:00 UTC, mpmdean commented
@shenmidelin can you check and sign off on these changes?

2022-01-29 15:32 UTC, merged